require('to_json')
  .use('html', require('html.to_json'), {circular: false})
  .use('xml', require('xml.to_json'), {circular: false})
  .use('yaml', require('yaml.to_json'))
  .use('markdown', require('markdown.to_json'))
  .use('svg', require('xml.to_json'), {circular: false})
  .use('csv', require('csv.to_json'))
  .use('cson', require('cson.to_json'))
  .use('hjson', require('hjson.to_json'))
  .use('rss', require('feed.to_json'))
  .use('atom', require('feed.to_json'))
  .use('feed', require('feed.to_json'))
